services:

  postgres:
    image: postgres
    environment:
        POSTGRES_PASSWORD: 123456
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fbarbar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    networks:
      - net
    ports:
      - 5050:80

networks:
  net: